### ISSUE TITLE
Read on closed response body

### ISSUE THREAD

**Issue by OGKevin** [igungor/putiofs#3]
Hey There,

Thanks for this library, finally I've found something that works, well partially 😝.

Every now and then I'm receiving this error message: 

```
putiofs: Error reading file <File ID: XXX Name: "XXX" Size: 30>: http: read on closed response body
````

This might be due to http 302 ?

**Comment by igungor** [comment]
Hey,

Thanks for the report! Unfortunately I'm not using putiofs for quite some time. Putio API might have changed, or there could be a bug on our side, I don't know. I don't have time to dig through this, sorry about that.

**Comment by OGKevin** [comment]
Hmm well that sucks 😔, unfortunately I dont know `Go` so guess ill have to look for another library then. Thanks anyway.

**Comment by igungor** [comment]
I don't know if you still use this program, I've made a couple of changes to the codebase that might fix your problem as well.

**Comment by OGKevin** [comment]
No i dont, ive found a python one which has been working perfectly. As i dont have Go knowledge i could not have fixed this issue myself.

**Comment by igungor** [comment]
Alright, I'm closing the issue.
